import os
from dotenv import load_dotenv

load_dotenv()
config = os.getenv

TOKEN = config("BOT_TOKEN")

FIREBASE_TYPE = config("FIREBASE_TYPE")
FIREBASE_PROJECT_ID = config("FIREBASE_PROJECT_ID")
FIREBASE_PRIVATE_KEY_ID = config("FIREBASE_PRIVATE_KEY_ID")
FIREBASE_PRIVATE_KEY = config("FIREBASE_PRIVATE_KEY").replace("\\n", "\n")
FIREBASE_CLIENT_EMAIL = config("FIREBASE_CLIENT_EMAIL")
FIREBASE_CLIENT_ID = config("FIREBASE_CLIENT_ID")
FIREBASE_AUTH_URI = config("FIREBASE_AUTH_URI")
FIREBASE_TOKEN_URI = config("FIREBASE_TOKEN_URI")
FIREBASE_AUTH_PROVIDER_X509_CERT_URL = config("FIREBASE_AUTH_PROVIDER_X509_CERT_URL")
FIREBASE_CLIENT_X509_CERT_URL = config("FIREBASE_CLIENT_X509_CERT_URL")
FIREBASE_DATABASE_URL = config("FIREBASE_DATABASE_URL")

BRO_ID = config("BRO_ID")
BRO_NAME = config("BRO_NAME")

SIS_ID = config("SIS_ID")
SIS_NAME = config("SIS_NAME")

SPECTATOR_IDS = config("SPECTATOR_IDS")
